#+TITLE: NixOS Configuration
#+AUTHOR: Bastiaan
#+PROPERTY: header-args:nix :tangle configuration.nix

* System Configuration
This file contains my NixOS system configuration in a literate format.
The focus of this NixOS config is light coding, audio production and a bit of gaming.

Every blocks needs to point at the configuration.nix for proper tangling, because of the {} and the start/end of the file.

* Packages

#+BEGIN_SRC nix :tangle configuration.nix
{ config, pkgs, ... }:
#+END_SRC

#+BEGIN_SRC nix :tangle configuration.nix
{ # this curly brace matche one in the final block of this document, DO NOT REMOVE
  imports = [
    # Include the results of the hardware scan (auto generated but can be enriched)
    ./hardware-configuration.nix
  ];
#+END_SRC

#+BEGIN_SRC nix :tangle configuration.nix
  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
#+END_SRC

* Network
** Defaults
#+BEGIN_SRC nix :tangle configuration.nix 
        # Network
        #network.networkmanager.enable = true;

        networking.hostName = "nixos"; # Define your hostname.
        # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

        # Configure network proxy if necessary
        # networking.proxy.default = "http://user:password@proxy:port/";
        # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

    # Open ports in the firewall like this:
          # networking.firewall.allowedTCPPorts = [ ... ];
          # networking.firewall.allowedUDPPorts = [ ... ];
          # Or disable the firewall altogether.
          # networking.firewall.enable = false;



        # Enable networking
        networking.networkmanager.enable = true;
#+END_SRC

** Timezones
#+BEGIN_SRC nix :tangle configuration.nix 
  # Set your time zone.
  time.timeZone = "Europe/Amsterdam";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "nl_NL.UTF-8";
    LC_IDENTIFICATION = "nl_NL.UTF-8";
    LC_MEASUREMENT = "nl_NL.UTF-8";
    LC_MONETARY = "nl_NL.UTF-8";
    LC_NAME = "nl_NL.UTF-8";
    LC_NUMERIC = "nl_NL.UTF-8";
    LC_PAPER = "nl_NL.UTF-8";

    LC_TELEPHONE = "nl_NL.UTF-8";
    LC_TIME = "nl_NL.UTF-8";
  };
#+END_SRC

** SSH
#+BEGIN_SRC nix :tangle configuration.nix
  # SSH connections
  programs.ssh = {
    startAgent = true;
    # Optional: add known hosts globally
    knownHosts = {
      github = {
        hostNames = [ "github.com" ];
        publicKey = "github.com,140.82.112.4 ssh-ed25519 AAAAC3NzaC1...";
      };
    };
  };

  services.openssh.enable = true;
#+END_SRC

* Desktop Environment
** DE Choice
#+BEGIN_SRC nix :tangle configuration.nix
    ### DESKTOP ENVIRONMENT ###
    # Enable the X11 windowing system.
    services.xserver.enable = true;

    # Enable the GNOME Desktop Environment.
    services.xserver.displayManager.gdm.enable = true;
    services.xserver.desktopManager.gnome.enable = true;
    
    # Unwanted packages that come with Gnome need to be excluded
    environment.gnome.excludePackages = (
      with pkgs;
      [
        atomix # puzzle game
        cheese # webcam tool
        epiphany # web browser
        evince # document viewer
        geary
        # email reader
        gedit # text editor
        gnome-characters
        gnome-music
        gnome-photos
        gnome-terminal
        gnome-tour
        hitori # sudoku game
        iagno # go game
        tali # poker game
        totem # video player
      ]
    );

#+END_SRC

** Theme
#+BEGIN_SRC nix :tangle configuration.nix
      ### THEME ###
      # Font
      fonts = {
        packages = with pkgs; [
          alegreya
        ];

        # font configuration
        fontconfig = {
          enable = true;
          defaultFonts = {
            serif = [ "Alegreya" ];
          };
        };
      };
#+END_SRC

* Hardware compatibility
** Keyboard layout
#+BEGIN_SRC nix :tangle configuration.nix
      # Configure keymap in X11
      services.xserver.xkb = {
        layout = "us";
        variant = "";
      };
#+END_SRC

** Printers
#+BEGIN_SRC nix :tangle configuration.nix
      # Enable CUPS to print documents.
      services.printing.enable = true;
#+END_SRC

** Mouse/touchpad
#+BEGIN_SRC nix :tangle configuration.nix
      # Enable touchpad support (enabled default in most desktopManager).
      # services.xserver.libinput.enable = true;
#+END_SRC

** Audio
#+BEGIN_SRC nix :tangle configuration.nix
      ### AUDIO ###
      # Enable sound with pipewire.
      services.pulseaudio.enable = false;
      security.rtkit.enable = true;
      services.pipewire = {
        enable = true;
        alsa.enable = true;
        alsa.support32Bit = true;
        pulse.enable = true;
        # If you want to use JACK applications, uncomment this
        jack.enable = true;

        # use the example session manager (no others are packaged yet so this is enabled by default,
        # no need to redefine it in your config for now)
        #media-session.enable = true;
      };
#+END_SRC

* Users
#+BEGIN_SRC nix :tangle configuration.nix
      # Define a user account. Don't forget to set a password with ‘passwd’.
      users.users.bastiaan = {
        isNormalUser = true;
        description = "bastiaan";
        extraGroups = [
          "networkmanager"
          "wheel"
        ];
        # User-specific package installations
        packages = with pkgs; [
          git
          wget
          unzip
        ];
      };
#+END_SRC

* Packages
** Install packages
List packages installed in system profile. To search available packages, run: $ nix search wget
#+BEGIN_SRC nix :tangle configuration.nix
          # $ nix search wget
          environment.systemPackages = with pkgs; [
            ## System basics ##
            firefox
            wget
            curl
            unzip
            openssh
            ## Software development-related ##
            git
            ghostty
            vim
            neovim
            emacs
            python3
            docker
            postgresql
            nixfmt-rfc-style # official nix formatter
            pgformatter # format postgres SQL
            lazygit # easy git interface for terminals
            yazi
            fd # file finding
            ripgrep
            luarocks # lua module support (neovim dependecy)
            ## Audio production ##
            reaper
            ## Entertainment ##
            spotify
            #steam
          ];
#+END_SRC

** Enable packages
Some programs need SUID wrappers, can be configured further or are started in user sessions:
      # programs.mtr.enable = true;
      # programs.gnupg.agent = {
      #   enable = true;
      #   enableSSHSupport = true;
      # };

#+BEGIN_SRC nix :tangle configuration.nix
      # Install firefox.
      programs.firefox.enable = true;

      # Allow unfree packages
      nixpkgs.config.allowUnfree = true;

      # Enable Docker
      virtualisation.docker.enable = true;
      virtualisation.docker.rootless.enable = true;

      # Emacs support
      services.emacs.enable = true;

#+END_SRC

* Nix release version
This value determines the NixOS release from which the default settings for stateful data, like file locations and database versions on your system were taken. 
It‘s perfectly fine and recommended to leave this value at the release version of the first install of this system.
Before changing this value read the documentation for this option (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
#+BEGIN_SRC nix :tangle configuration.nix
      system.stateVersion = "25.05"; # Did you read the comment?

    }
#+end_src
